# Generated by Django 3.2.5 on 2021-07-14 10:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=1000000)),
                ('product_description', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=1000)),
                ('s_n', models.CharField(max_length=1000)),
                ('hospital', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('installtion_service_contract_doc_no', models.CharField(max_length=1000)),
                ('installed_service_contract_date', models.CharField(max_length=1000)),
                ('first_date', models.CharField(max_length=1000)),
                ('first_doc_no', models.CharField(max_length=1000)),
                ('first_provider', models.CharField(max_length=1000)),
                ('first_remark', models.CharField(max_length=1000)),
                ('second_date', models.CharField(max_length=1000)),
                ('second_doc_no', models.CharField(max_length=1000)),
                ('second_provider', models.CharField(max_length=1000)),
                ('second_remark', models.CharField(max_length=1000)),
                ('third_date', models.CharField(max_length=1000)),
                ('third_doc_no', models.CharField(max_length=1000)),
                ('third_provider', models.CharField(max_length=1000)),
                ('third_remark', models.CharField(max_length=1000)),
                ('fourth_date', models.CharField(max_length=1000)),
                ('fourth_doc_no', models.CharField(max_length=1000)),
                ('fourth_provider', models.CharField(max_length=1000)),
                ('fourth_remark', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2021, 7, 14, 10, 1, 0, 270212, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
