# Generated by Django 3.2.5 on 2021-10-18 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 5, 37, 52, 360780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 5, 37, 52, 359688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 5, 37, 52, 360200, tzinfo=utc)),
        ),
    ]
