# Generated by Django 3.2.5 on 2021-10-13 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrecord',
            name='case_no',
            field=models.CharField(default='N/A', max_length=10485760),
        ),
        migrations.AlterField(
            model_name='installationrecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 52, 31, 150043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 52, 31, 148520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='no',
            field=models.CharField(default='N/A', max_length=10485760),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='case_no',
            field=models.CharField(default='N/A', max_length=10485760),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 52, 31, 149036, tzinfo=utc)),
        ),
    ]
