# Generated by Django 3.2.5 on 2021-07-26 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210714_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='brand',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='city',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 10, 25, 16, 648338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='first_date',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='first_doc_no',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='first_provider',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='first_remark',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='fourth_date',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='fourth_doc_no',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='fourth_provider',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='fourth_remark',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='hospital',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='installed_service_contract_date',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='installtion_service_contract_doc_no',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='model',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='no',
            field=models.CharField(default='N/A', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='product_description',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='s_n',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='second_date',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='second_doc_no',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='second_provider',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='second_remark',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='third_date',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='third_doc_no',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='third_provider',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='third_remark',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
