# Generated by Django 3.2.5 on 2021-10-14 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211013_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 8, 58, 57, 724364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 8, 58, 57, 722916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 8, 58, 57, 723407, tzinfo=utc)),
        ),
    ]
