# Generated by Django 3.2.5 on 2021-10-14 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211014_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 9, 47, 1, 166147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 9, 47, 1, 164622, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 9, 47, 1, 165140, tzinfo=utc)),
        ),
    ]
