# Generated by Django 3.2.5 on 2021-08-02 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210726_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 7, 47, 51, 217790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='no',
            field=models.CharField(default='N/A', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='product_description',
            field=models.TextField(default='N/A', max_length=10000),
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(default='N/A', max_length=100000000)),
                ('date', models.CharField(default='N/A', max_length=1000)),
                ('time', models.CharField(default='N/A', max_length=1000)),
                ('name_of_hospital', models.CharField(default='N/A', max_length=1000)),
                ('contact_person', models.CharField(default='N/A', max_length=1000)),
                ('contact_number', models.CharField(default='N/A', max_length=1000)),
                ('product_description', models.TextField(default='N/A', max_length=10000)),
                ('brand', models.CharField(default='N/A', max_length=1000)),
                ('model', models.CharField(default='N/A', max_length=1000)),
                ('s_n', models.CharField(default='N/A', max_length=1000)),
                ('complaint', models.CharField(default='N/A', max_length=1000)),
                ('referred_by', models.CharField(default='N/A', max_length=1000)),
                ('receiver_name', models.CharField(default='N/A', max_length=1000)),
                ('receive_date', models.CharField(default='N/A', max_length=1000)),
                ('receive_time', models.CharField(default='N/A', max_length=1000)),
                ('assign_by', models.CharField(default='N/A', max_length=1000)),
                ('assign_date', models.CharField(default='N/A', max_length=1000)),
                ('assign_time', models.CharField(default='N/A', max_length=1000)),
                ('expected_duration', models.CharField(default='N/A', max_length=1000)),
                ('assign_to', models.CharField(default='N/A', max_length=1000)),
                ('remark', models.CharField(default='N/A', max_length=1000)),
                ('open_close', models.CharField(default='N/A', max_length=1000)),
                ('service_report_doc_no', models.CharField(default='N/A', max_length=1000)),
                ('inspection', models.CharField(default='N/A', max_length=1000)),
                ('repair_description', models.TextField(default='N/A', max_length=10000)),
                ('spare_part_request_doc_no', models.CharField(default='N/A', max_length=1000)),
                ('warranty_card_no', models.CharField(default='N/A', max_length=1000)),
                ('service_start_date', models.CharField(default='N/A', max_length=1000)),
                ('service_finished_date', models.CharField(default='N/A', max_length=1000)),
                ('service_total_time', models.CharField(default='N/A', max_length=1000)),
                ('service_remark', models.CharField(default='N/A', max_length=1000)),
                ('recorded_by', models.CharField(default='N/A', max_length=1000)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 7, 47, 51, 218303, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
