# Generated by Django 3.2.5 on 2021-08-04 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210802_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='installtion_service_contract_doc_no',
            new_name='installation_service_contract_doc_no',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='remark',
            new_name='assign_order_remark',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 10, 38, 32, 165251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 10, 38, 32, 165765, tzinfo=utc)),
        ),
    ]
