# Generated by Django 3.2.5 on 2021-08-08 10:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20210804_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 10, 5, 41, 964354, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 10, 5, 41, 964880, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='InstallationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(default='N/A', max_length=100000000)),
                ('date', models.CharField(default='N/A', max_length=1000)),
                ('time', models.CharField(default='N/A', max_length=1000)),
                ('name_of_hospital', models.CharField(default='N/A', max_length=1000)),
                ('address', models.CharField(default='N/A', max_length=1000)),
                ('contact_person', models.CharField(default='N/A', max_length=1000)),
                ('contact_number', models.CharField(default='N/A', max_length=1000)),
                ('product_description', models.TextField(default='N/A', max_length=10000)),
                ('brand', models.CharField(default='N/A', max_length=1000)),
                ('model', models.CharField(default='N/A', max_length=1000)),
                ('s_n', models.CharField(default='N/A', max_length=1000)),
                ('referred_by', models.CharField(default='N/A', max_length=1000)),
                ('receiver_name', models.CharField(default='N/A', max_length=1000)),
                ('receive_date', models.CharField(default='N/A', max_length=1000)),
                ('receive_time', models.CharField(default='N/A', max_length=1000)),
                ('assign_by', models.CharField(default='N/A', max_length=1000)),
                ('assign_date', models.CharField(default='N/A', max_length=1000)),
                ('assign_time', models.CharField(default='N/A', max_length=1000)),
                ('expected_duration', models.CharField(default='N/A', max_length=1000)),
                ('assign_to', models.CharField(default='N/A', max_length=1000)),
                ('assign_remark', models.CharField(default='N/A', max_length=1000)),
                ('installation_doc_no', models.CharField(default='N/A', max_length=1000)),
                ('ref_inovice_contract_no', models.CharField(default='N/A', max_length=1000)),
                ('installed_date', models.CharField(default='N/A', max_length=1000)),
                ('installed_by', models.CharField(default='N/A', max_length=1000)),
                ('service_contact_package', models.CharField(default='N/A', max_length=1000)),
                ('warranty_card_no', models.CharField(default='N/A', max_length=1000)),
                ('machine_warranty_expiry_date', models.CharField(default='N/A', max_length=1000)),
                ('service_warranty_expiry_date', models.CharField(default='N/A', max_length=1000)),
                ('installation_duration', models.CharField(default='N/A', max_length=1000)),
                ('record_by', models.CharField(default='N/A', max_length=1000)),
                ('installation_remark', models.CharField(default='N/A', max_length=1000)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2021, 8, 8, 10, 5, 41, 965871, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
