# Generated by Django 3.2.5 on 2021-08-09 08:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20210808_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 8, 33, 56, 46843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 8, 33, 56, 45301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 8, 33, 56, 45824, tzinfo=utc)),
        ),
    ]
